name: Dashboard Image Renderer
version: 1.4.1
slug: dashboard-image-renderer
description: This addon renders an image of a Home Assistant Lovelace dashboard and serves it over HTTP.
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
url: 'https://github.com/iclanton/hass-dashboard-renderer'
image: 'iclanton/hass-dashboard-renderer-ha-addon-{arch}'
webui: 'http://[HOST]:[PORT:5000]'
ingress: true
ingress_port: 5000
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: 'Node Webserver hosting rendered image'
map:
  - media:rw
watchdog: 'http://[HOST]:[PORT:5000]/'
init: false
options:
  HA_BASE_URL: 'https://your-path-to-home-assistant:8123'
  HA_SCREENSHOT_URL: '/lovelace/0'
  HA_ACCESS_TOKEN: ''
  INCLUDE_CACHE_BREAK_QUERY: false
  LANGUAGE: 'en'
  CRON_JOB: '* * * * *'
  RENDERING_TIMEOUT: '60000'
  RENDERING_DELAY: '0'
  RENDERING_SCREEN_HEIGHT: '800'
  RENDERING_SCREEN_WIDTH: '600'
  BROWSER_LAUNCH_TIMEOUT: '30000'
  LEAVE_IMAGE_UNMODIFIED: false
  ROTATION: '0'
  SCALING: '1'
  GRAYSCALE_DEPTH: '8'
  IMAGE_FORMAT: 'png'
  COLOR_MODE: 'GrayScale'
  REMOVE_GAMMA: true
  PREFERS_COLOR_SCHEME: 'light'
  HA_BATTERY_WEBHOOK: ''
  EAGER_RERENDER: false
  ADDITIONAL_ENV_VARS: []
schema:
  HA_BASE_URL: 'url'
  HA_SCREENSHOT_URL: 'str'
  HA_ACCESS_TOKEN: 'password'
  INCLUDE_CACHE_BREAK_QUERY: 'bool?'
  LANGUAGE: 'str?'
  CRON_JOB: 'str?'
  RENDERING_TIMEOUT: 'int?'
  RENDERING_DELAY: 'int?'
  RENDERING_SCREEN_HEIGHT: 'int?'
  RENDERING_SCREEN_WIDTH: 'int?'
  BROWSER_LAUNCH_TIMEOUT: 'int?'
  LEAVE_IMAGE_UNMODIFIED: 'bool?'
  ROTATION: 'int?'
  SCALING: 'float?'
  GRAYSCALE_DEPTH: 'int?'
  IMAGE_FORMAT: 'list(png|jpeg)?'
  COLOR_MODE: 'list(GrayScale|TrueColor)?'
  REMOVE_GAMMA: 'bool?'
  PREFERS_COLOR_SCHEME: 'list(light|dark)?'
  HA_BATTERY_WEBHOOK: 'str?'
  EAGER_RERENDER: 'bool?'
  ADDITIONAL_ENV_VARS:
    - name: match(^[A-Z0-9_]+$)
      value: str
environment:
  output_path: '/output/cover'
