name: ci

on:
  push:
    tags: [ 'v*.*.*' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - displayName: 'Default'
            platforms: linux/amd64,linux/arm/v7,linux/arm64
            buildArgs: ''
            tagSuffix: ''
            dockerfile: './Dockerfile'
          - displayName: 'HA-AMD64'
            platforms: 'linux/amd64'
            buildArgs: 'BUILD_FROM=homeassistant/amd64-base:latest'
            tagSuffix: '-ha-addon-amd64'
            dockerfile: './Dockerfile.HA_ADDON'
          - displayName: 'HA-ARM64'
            platforms: 'linux/arm64/v8'
            buildArgs: 'BUILD_FROM=homeassistant/aarch64-base:latest'
            tagSuffix: '-ha-addon-aarch64'
            dockerfile: './Dockerfile.HA_ADDON'
          - displayName: 'HA-ARMV7'
            platforms: 'linux/arm/v7'
            buildArgs: 'BUILD_FROM=homeassistant/armv7-base:latest'
            tagSuffix: '-ha-addon-armv7'
            dockerfile: './Dockerfile.HA_ADDON'

    name: Push to Docker (${{ matrix.displayName }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.buildArgs }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            iclanton/hass-dashboard-renderer${{ matrix.tagSuffix }}:${{ env.PACKAGE_VERSION }},
            iclanton/hass-dashboard-renderer${{ matrix.tagSuffix }}:latest
